; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29333.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\assembly\func1\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?AddNum@@YAHHH@Z				; AddNum
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?AddNum@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?AddNum@@YAHHH@Z PROC					; AddNum, COMDAT

; 4    : {

	push	ebp
	mov	ebp, esp

; 5    :     return a + b;

	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]

; 6    : }

	pop	ebp
	ret	0
?AddNum@@YAHHH@Z ENDP					; AddNum
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -4						; size = 4
_main	PROC						; COMDAT

; 9    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 10   :     int c;
; 11   :     c = AddNum(123, 456);

	push	456					; 000001c8H
	push	123					; 0000007bH
	call	?AddNum@@YAHHH@Z			; AddNum
	add	esp, 8
	mov	DWORD PTR _c$[ebp], eax

; 12   : 
; 13   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
