//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by URLTree.rc
//
#define IDS_PROJNAME                    100
#define IDB_URLTREEVIEW                 101
#define IDR_URLTREEVIEW                 102
#define IDS_TITLEURLPage                103
#define IDS_HELPFILEURLPage             104
#define IDS_DOCSTRINGURLPage            105
#define IDR_URLPAGE                     106
#define IDD_URLPAGE                     107
#define IDB_IMAGE                       201
#define IDC_NAME                        201
#define IDB_SELECT                      202
#define IDC_URL                         202
#define IDB_TOOL                        203
#define IDC_ADD                         203
#define IDC_REMOVE                      204
#define IDC_VALUES                      205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         206
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
