; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29112.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\assembly\func1\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?return_int_arg1@@YAHH@Z			; return_int_arg1
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?return_int_arg1@@YAHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
?return_int_arg1@@YAHH@Z PROC				; return_int_arg1, COMDAT

; 7    : {

	push	ebp
	mov	ebp, esp

; 8    :     return a;

	mov	eax, DWORD PTR _a$[ebp]

; 9    : }

	pop	ebp
	ret	0
?return_int_arg1@@YAHH@Z ENDP				; return_int_arg1
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -4						; size = 4
_main	PROC						; COMDAT

; 12   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 13   :     int c;
; 16   :     c = return_int_arg1(120);

	push	120					; 00000078H
	call	?return_int_arg1@@YAHH@Z		; return_int_arg1
	add	esp, 4
	mov	DWORD PTR _c$[ebp], eax

; 17   : 
; 18   :     return 0;

	xor	eax, eax

; 19   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
