; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29333.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\assembly\func1\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?MySub3@@YAXXZ					; MySub3
PUBLIC	?MySub2@@YAXXZ					; MySub2
PUBLIC	?MySub1@@YAXXZ					; MySub1
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?MySub1@@YAXXZ
_TEXT	SEGMENT
?MySub1@@YAXXZ PROC					; MySub1, COMDAT

; 3    : void MySub1() {

	push	ebp
	mov	ebp, esp

; 4    : 
; 5    : }

	pop	ebp
	ret	0
?MySub1@@YAXXZ ENDP					; MySub1
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?MySub2@@YAXXZ
_TEXT	SEGMENT
?MySub2@@YAXXZ PROC					; MySub2, COMDAT

; 7    : void MySub2() {

	push	ebp
	mov	ebp, esp

; 8    : 
; 9    : }

	pop	ebp
	ret	0
?MySub2@@YAXXZ ENDP					; MySub2
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?MySub3@@YAXXZ
_TEXT	SEGMENT
?MySub3@@YAXXZ PROC					; MySub3, COMDAT

; 11   : void MySub3() {

	push	ebp
	mov	ebp, esp

; 12   : 
; 13   : }

	pop	ebp
	ret	0
?MySub3@@YAXXZ ENDP					; MySub3
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_a$ = -4						; size = 4
_main	PROC						; COMDAT

; 16   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 17   : 	int a = 123;

	mov	DWORD PTR _a$[ebp], 123			; 0000007bH

; 18   : 	
; 19   : 	if (a > 100) {

	cmp	DWORD PTR _a$[ebp], 100			; 00000064H
	jle	SHORT $LN2@main

; 20   : 		MySub1();

	call	?MySub1@@YAXXZ				; MySub1

; 21   : 	}

	jmp	SHORT $LN1@main
$LN2@main:

; 22   : 	else if (a < 50) {

	cmp	DWORD PTR _a$[ebp], 50			; 00000032H
	jge	SHORT $LN4@main

; 23   : 		MySub2();

	call	?MySub2@@YAXXZ				; MySub2

; 24   : 	}

	jmp	SHORT $LN1@main
$LN4@main:

; 25   : 	else
; 26   : 	{
; 27   : 		MySub3();

	call	?MySub3@@YAXXZ				; MySub3
$LN1@main:

; 28   : 	}
; 29   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
