; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29112.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\assembly\func1\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?add@@YAHHH@Z					; add
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?add@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4 //メモリの相対アドレス？一時変数につけられる。
_b$ = 12						; size = 4 //メモリの相対アドレス？一時変数につけられる。
?add@@YAHHH@Z PROC					; add, COMDAT

; 2    : {

	push	ebp
	mov	ebp, esp;ベースポインタはスタックポインタに。

; 3    :     return a + b;

	mov	eax, DWORD PTR _a$[ebp];DWORDは32bit(int型) 
	add	eax, DWORD PTR _b$[ebp];戻り値はeaxに格納される

; 4    : }

	pop	ebp
	ret	0
?add@@YAHHH@Z ENDP					; add
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -4						; size = 4 //メモリの相対アドレス？一時変数につけられる。
_main	PROC						; COMDAT

; 7    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 8    :     int c;
; 9    :     c = add(100, 123);

	push	123					; 0000007bH 引数の後ろからスタックに置く
	push	100					; 00000064H
	call	?add@@YAHHH@Z				; add
	add	esp, 8
	mov	DWORD PTR _c$[ebp], eax;addの戻り値を変数cに格納

; 10   : 
; 11   :     return 0;

	xor	eax, eax;値をクリア

; 12   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
