; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29333.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\assembly\func1\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?MySub@@YAXXZ					; MySub
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT ?MySub@@YAXXZ
_TEXT	SEGMENT
?MySub@@YAXXZ PROC					; MySub, COMDAT

; 3    : void MySub() {

	push	ebp
	mov	ebp, esp

; 4    : 
; 5    : }

	pop	ebp
	ret	0
?MySub@@YAXXZ ENDP					; MySub
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\Assembly\func1\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_i$ = -4						; size = 4
_main	PROC						; COMDAT

; 8    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 9    : 	int i;
; 10   : 	for (i = 0; i < 10; i++) {

	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN4@main
$LN2@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN4@main:
	cmp	DWORD PTR _i$[ebp], 10			; 0000000aH
	jge	SHORT $LN1@main

; 11   : 		MySub();

	call	?MySub@@YAXXZ				; MySub

; 12   : 	}

	jmp	SHORT $LN2@main
$LN1@main:

; 13   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
