; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	c:\users\matsumotominoru\desktop\visual studio 2019\c++_console\consoletemplate\consoleapplication1\consoleapplication1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
; Function compile flags: /Ogtp
; File C:\Users\MatsumotoMinoru\Desktop\Visual Studio 2019\C++_Console\ConsoleTemplate\ConsoleApplication1\ConsoleApplication1.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 3    : 	return 0;

	xor	eax, eax

; 4    : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
