//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SetEvent.rc
//
#define IDD_SETEVENT_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDI_GO                          129
#define IDI_READY                       130
#define IDI_STOP                        131
#define IDC_EVENTNAME                   1000
#define IDC_CREATE                      1001
#define IDC_GO                          1004
#define IDC_STOP                        1005
#define IDC_STATUS                      1006
#define IDC_EVENTS                      1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
